In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])
a

array([1, 2, 3, 4])

In [2]:
b = a.reshape(2,2)
b

array([[1, 2],
       [3, 4]])

In [3]:
# reshape(-1, 1)的意思是定义列是1个，行根据列来变化。
c = a.reshape(-1, 1)
c

array([[1],
       [2],
       [3],
       [4]])

In [6]:
vec_1 = [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1]
vec_2 = [2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2]
vec_1 = np.array(vec_1)
vec_2 = np.array(vec_2)
print(vec_1 - vec_2)
print(np.square(vec_1 - vec_2))
print(np.sum(np.square(vec_1 - vec_2)))
print(np.sqrt(np.sum(np.square(vec_1 - vec_2))))
print(np.linalg.norm(vec_1 - vec_2))

[-2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -2 -1 -1]
[4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 1 1]
74
8.602325267042627
8.602325267042627


In [7]:
np.dot(vec_1, vec_2)

4