In [ ]:
import torch
import torch.nn as nn

In [ ]:
"""
view()函数经常使用用来调整输入之类的。
另外，就想view()暗示的，下游的数据是共享的。改变x，就会改变y和z。
"""
x = torch.randn(4, 4)
print(x)
y = x.view(16)
print(y)
"""
the size -1 表示本维度从其他维度推断
"""
z = x.view(-1, 8) 
print(z)

In [ ]:
a = torch.ones([4, 3])
print(a)
b = torch.zeros([4, 3])
print(b)

In [ ]:
"""
Tensor经常用的操作
exp - 求exp, 可以输入二维数组
sum - 返回标量，不管输入的是几维
/ - 元素除
"""
c = torch.Tensor([[-1, 1, 2], [2, 2, 4]])
c_exp = c.exp()
print(c_exp)
c_sum = c.sum()
print(c_sum)
c_divide = c / c_sum
print(c_divide)

In [ ]:
"""
Tensor常用函数
Softmax = exp{xi} / sum(exp{x1~xn})
"""
softmax_func = nn.Softmax(dim = 1)
c_softmax = softmax_func(c)
print(c_softmax)

x_input = torch.randn(1, 5)
print('x_input:\n',x_input)
y_target = torch.tensor([1])
print('y_target\n',y_target)
crossentropyloss = nn.CrossEntropyLoss()
crossentropyloss_output = crossentropyloss(x_input, y_target)
print(crossentropyloss_output)

In [27]:
"""
一些权重初始化的方法
bias一般用torch.zeors
"""
d = torch.randn([10, 10])
print(d)

d_normal = torch.nn.init.normal(d, 0, 1)
print(d_normal)

d_uniform = torch.nn.init.uniform(d, 0, 10)
print(d_uniform)

w = torch.empty(3, 5)
nn.init.constant_(w, 0.3)
print(w)

tensor([[ 0.6606,  0.6161, -2.2126,  0.7239, -0.8800, -0.5093, -0.2204, -2.6573,
         -0.1996,  0.5197],
        [ 0.0089,  0.8361, -0.5583,  2.9509, -0.3524,  0.7096,  0.5880,  1.8533,
         -1.0699,  0.2808],
        [-1.1662, -0.5931, -1.8854, -0.0228, -1.8701, -0.6706,  0.3164,  2.0999,
         -1.0327,  0.3815],
        [ 1.1616,  0.4180, -0.2799, -0.3442, -0.6191, -0.8332, -0.0309, -0.5014,
          0.2701, -0.1007],
        [-0.3910, -0.2104,  0.5259,  0.5686,  0.1873, -0.5559,  0.7013, -0.6480,
          0.4182, -1.6324],
        [ 0.7926,  0.2358, -0.4525,  0.4091,  0.7298, -0.1931,  0.2297,  3.1296,
          0.6238,  0.1907],
        [ 1.8421, -0.7676,  0.5441,  0.7879,  1.9754,  0.9419, -0.1103,  0.6144,
         -0.1063,  1.5264],
        [-1.0438, -0.3680,  1.1349,  0.2266,  0.8170, -2.2181, -0.2638,  0.2709,
          0.2737, -0.1156],
        [-0.8316, -0.1483, -0.0369, -1.1189,  1.6014, -1.2266,  0.1530,  0.5439,
         -2.1138,  1.3250],
        [-1.8302, -

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  # This is added back by InteractiveShellApp.init_path()


In [26]:
f = torch.Tensor([[-1, 1, 2], [2, 2, 4]])
print(f)
f = f.float()
print(f)

tensor([[-1.,  1.,  2.],
        [ 2.,  2.,  4.]])
tensor([[-1.,  1.,  2.],
        [ 2.,  2.,  4.]])
