In [2]:
"""
比较numpy和torch tensor操作
其他的math运算见http://pytorch.org/docs/torch.html#math-operations
也可以https://pytorch.org/docs/stable/torch.html来查找定义
需要熟悉其中的一些操作，这样才能自己实现一些东西
一些基本操作都要放在这个文件
"""

import torch
import numpy as np
import torch.nn as nn

In [6]:
# dot，注意numpy中的dot操作其实跟矩阵乘法类似，但是torch的tensor操作是不一样的。
data = [[1,2], [3,4]]
tensor = torch.FloatTensor(data)  # 32-bit floating point
data = np.array(data)
tensor_flatten = torch.flatten(tensor)
print(
    '\ndot',
    '\nnumpy: \n', data.dot(data),     # [[7, 10], [15, 22]]
    #'\ntorch: \n', torch.dot(tensor, tensor)   # 现在二维的已经不支持直接这样做了。
    '\ntorch: \n', torch.dot(tensor_flatten, tensor_flatten)  # 30
)

# cat
"""
对于2d，可以简单的认为
dim0的cat是将添加行+重新组织矩阵，dim1的cat是添加列+重新组织矩阵
"""
tensor_2d = torch.Tensor([[1,2],[4,5]]) 
dim0_cat = torch.cat((tensor_2d, tensor_2d, tensor_2d), 0)
print("\ndim 0 cat")
print(dim0_cat)
dim1_cat = torch.cat((tensor_2d, tensor_2d, tensor_2d), 1)
print("\ndim 1 cat")
print(dim1_cat)

# reduce操作
tensor_2d = torch.Tensor([[1,2],[4,5],[7,8]]) 
print("\norigin tensor")
print(tensor_2d)
print("\ndim 0 reduce")
print(torch.sum(tensor_2d, dim=0))
print("\ndim 1 reduce")
print(torch.sum(tensor_2d, dim=1))

# 矩阵乘法
print("\nMatrix x Matrix")
tensor1 = torch.Tensor([[1,2,3], [4,5,6]])  # 2*3的矩阵
tensor2 = torch.Tensor([[0],[1],[0]]) # 3*1矩阵
print(torch.mm(tensor1, tensor2)) # 2*1的矩阵, mm - matrix matrix

# topk，这种输入一般是比较常见的，就是传出来多个预测概率数组，一次计算所有的。
tensorx = torch.Tensor([[.1, .2, .7], [.4, .5, .1]])
print(tensorx)
# 这里跟我想的有点不一样，dim=1返回的才是想要的。
print(torch.topk(tensorx, 2, dim=1))


dot 
numpy: 
 [[ 7 10]
 [15 22]] 
torch: 
 tensor(30.)

dim 0 cat
tensor([[1., 2.],
        [4., 5.],
        [1., 2.],
        [4., 5.],
        [1., 2.],
        [4., 5.]])

dim 1 cat
tensor([[1., 2., 1., 2., 1., 2.],
        [4., 5., 4., 5., 4., 5.]])

origin tensor
tensor([[1., 2.],
        [4., 5.],
        [7., 8.]])

dim 0 reduce
tensor([12., 15.])

dim 1 reduce
tensor([ 3.,  9., 15.])

Matrix x Matrix
tensor([[2.],
        [5.]])
tensor([[0.1000, 0.2000, 0.7000],
        [0.4000, 0.5000, 0.1000]])
torch.return_types.topk(
values=tensor([[0.7000, 0.2000],
        [0.5000, 0.4000]]),
indices=tensor([[2, 1],
        [1, 0]]))


In [ ]:
print("\n1d index and slicing")
# 1d index and slicing
print(tensor[1])
print(tensor[-1])
print(tensor[1:])
# 2d index index and slicing
tensor_2d = torch.Tensor([[1,2,3],[4,5,6], [7,8,9]]) 
print(tensor_2d)
print("\n2d index and slicing")
print(tensor_2d[0])
# 左闭合右开，如果两边相等，则不取
print(tensor_2d[0:1, :])
print(tensor_2d[1:2, :])
print(tensor_2d[2:3, :])
print(tensor_2d[:, 0:1])
print(tensor_2d[:, 1:2])
print(tensor_2d[:, 2:3])
# 最右下角
print(tensor_2d[1:3, 1:3])

# abs
data = [-1, -2, 1, 2]
tensor = torch.FloatTensor(data)  # 32-bit floating point
print(
    '\nabs',
    '\nnumpy: \n', np.abs(data),          # [1 2 1 2]
    '\ntorch: \n', torch.abs(tensor)      # [1 2 1 2]
)
data_2d = np.array([-1, -2, 1, 2]).reshape((2,2))
tensor_2d = torch.FloatTensor(data_2d)
print(
    '\n2d abs',
    '\nnumpy: \n', np.abs(data_2d),         
    '\ntorch: \n', torch.abs(tensor_2d)     
)

# mean
data = [-1, -2, 1, 2]
tensor = torch.FloatTensor(data)  # 32-bit floating point
print(
    '\nmean',
    '\nnumpy: \n', np.mean(data),         # 0.0
    '\ntorch: \n', torch.mean(tensor)     # 0.0
)

data_2d = np.array([-1, -2, 1, 2]).reshape((2,2))
tensor_2d = torch.FloatTensor(data_2d)
print(
    '\n2d mean',
    '\nnumpy: \n', np.mean(data_2d),         # 0.0
    '\ntorch: \n', torch.mean(tensor_2d)     # 0.0
)

# add, 基于元素的
print("\nadd")
x1 = torch.Tensor([[1,2],[4,5]])  
x2 = torch.Tensor([[1,2],[4,5]]) 
y1 = x1 + x2
y2 = torch.add(x1, x2)
y3 = x1.add(x2)
print(y1)
print(y2)
print(y3)

# *，基于元素的
print("\ntensor *")
tensor_2d = torch.Tensor([[1,2],[4,5]]) 
print(tensor_2d * tensor_2d)

# 元素级别的比较
tensor_2d_1 = torch.Tensor([[1,2],[4,5],[7,8]]) 
tensor_2d_2 = torch.Tensor([[1,2],[4,5],[7,9]]) 
print("\nelement equal")
print(torch.eq(tensor_2d_1,tensor_2d_2))


# 这个操作比较违反直觉
print("\n# Matrix X vector")
tensor1 = torch.Tensor([[1,2,3], [4,5,6]]) # 2*3
tensor2 = torch.Tensor([0,1,0]) # 1*3
print(torch.mv(tensor1, tensor2)) # 1*2, mv - matrix vector

In [ ]:
# is_tensor
print(torch.is_tensor(np_data))
print(torch.is_tensor(tensor))