In [1]:
import torch
import numpy as np
import torch.nn as nn

In [4]:
"""
tensor初始化
"""
print("\nsimple initilization")
v1 = torch.Tensor(2, 3)          # An un-initialized torch.FloatTensor of size 2x3
v2 = torch.Tensor([[1,2],[4,5]]) # A Tensor initialized with a specific array
v3 = torch.LongTensor([1,2,3])   # A Tensor of type Long
print(v1)
print(v2)
print(v3)

print("\nset mannal seed, stable result")
# 使用这个可以得到一样的v1,v2,v3
torch.manual_seed(1)
v1 = torch.rand(2, 3)            # Initialize with random number (uniform distribution)
v2 = torch.randn(2, 3)           # With normal distribution (SD=1, mean=0)
v3 = torch.randperm(4)
print(v1)
print(v2)
print(v3)

print("\nfrom np array")
# 共享存储空间
np_data = np.arange(6).reshape((2, 3))
tensor = torch.from_numpy(np_data)
print(tensor)

print("\nfrom normal array")
array = [-1, -2, 1, 2]
tensor = torch.FloatTensor(array) 
print(tensor)

print("\nnp array like style")
v1 = torch.arange(5)             # similar to range(5) but creating a Tensor
v2 = torch.arange(0, 5, step=1)  # Size 5. Similar to range(0, 5, 1)
print(v1)
print(v2)

print("\nfill 0 and 1")
v1 = torch.ones((2,3)) 
v2 = torch.zeros((2,3))
print(v1)
print(v2)

print("\nimportant - always used to init weight")
v1 = torch.Tensor(2, 2).uniform_(0, 1)
print(v1)

print("\n empty")
tensor = torch.empty((2,3,3))
print(tensor)
print(tensor.size(0))
print(tensor.size(1))
print(tensor.size(2))


simple initilization
tensor([[9.8091e-45, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[1., 2.],
        [4., 5.]])
tensor([1, 2, 3])

set mannal seed, stable result
tensor([[0.7576, 0.2793, 0.4031],
        [0.7347, 0.0293, 0.7999]])
tensor([[ 0.5636,  1.1431,  0.8590],
        [ 0.7056, -0.3406, -1.2720]])
tensor([2, 0, 1, 3])

from np array
tensor([[0, 1, 2],
        [3, 4, 5]])

from normal array
tensor([-1., -2.,  1.,  2.])

np array like style
tensor([0, 1, 2, 3, 4])
tensor([0, 1, 2, 3, 4])

fill 0 and 1
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])

important - always used to init weight
tensor([[0.1980, 0.4162],
        [0.2843, 0.3398]])

 empty
tensor([[[ 0.0000e+00, -3.6893e+19,  0.0000e+00],
         [-3.6893e+19,  6.6869e+31,  1.0646e+24],
         [ 7.7128e+31,  1.0646e+24,  2.8260e+23]],

        [[ 7.2716e+31,  1.7743e+28,  1.3458e-14],
         [ 1.4326e-19,  2.7909e+23,  6.6908e+31],
     

In [5]:
"""
一些权重初始化的方法
bias一般用torch.zeors
"""
d = torch.randn([10, 10])
print(d)

d_normal = torch.nn.init.normal(d, 0, 1)
print(d_normal)

d_uniform = torch.nn.init.uniform(d, 0, 10)
print(d_uniform)

w = torch.empty(3, 5)
nn.init.constant_(w, 0.3)


tensor([[ 1.1712,  1.7674, -0.0954,  0.1394, -1.5785, -0.3206, -0.2993,  1.8793,
          0.3357,  0.2753],
        [ 1.7163, -0.0561,  0.9107, -1.3924,  2.6891, -0.1110, -0.7765,  2.0242,
         -0.0865,  0.0981],
        [-1.2150,  0.7312,  1.1718, -0.9274,  0.2786,  0.2468,  1.1843, -0.7282,
          1.1633, -0.0091],
        [-0.8425,  0.1374, -0.5242, -1.8034, -1.3083,  0.4533,  1.1422,  0.2486,
         -1.7754, -0.0255],
        [ 0.2981,  0.1099, -0.6463,  0.4285,  1.4761, -1.7869,  1.6103, -0.7040,
          0.8793, -1.4504],
        [-1.1802,  0.4100,  0.4085,  0.2579,  1.0950, -0.5065,  0.8547, -0.2805,
          0.7000, -1.4567],
        [ 1.6089,  0.0938, -1.2597,  0.2546, -1.4746, -0.3416, -0.3003,  1.3075,
         -1.1628,  0.1196],
        [-0.1631,  0.6614, -0.9301,  1.4301,  0.4208, -0.3538,  0.7639, -0.5890,
         -0.7636,  1.3352],
        [ 0.1938, -2.5832,  0.8539,  1.2466,  0.3476,  0.0930,  0.6147,  0.7124,
         -1.7765,  0.3539],
        [ 1.1996, -

/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:8: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  
/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:11: UserWarning: nn.init.uniform is now deprecated in favor of nn.init.uniform_.
  # This is added back by InteractiveShellApp.init_path()


tensor([[0.3000, 0.3000, 0.3000, 0.3000, 0.3000],
        [0.3000, 0.3000, 0.3000, 0.3000, 0.3000],
        [0.3000, 0.3000, 0.3000, 0.3000, 0.3000]])