In [1]:
"""
会改变tensor的形状。
这个经常要使用，为什么？
因为：
1. 某些操作要求形状满足一定的情况。例如矩阵乘法。
2. 某些module要求输入满足一定的情况。例如nn.RNN等。
3. 某些函数要求形状满足一定的要求。例如fit_on_text(), topk等。
"""
import torch
import numpy as np
import torch.nn as nn

In [2]:
tensor_3d = torch.Tensor([[[1,2,3]], [[4,5,6]], [[7,8,9]]])
print(tensor_3d)
print(tensor_3d.size())

tensor([[[1., 2., 3.]],

        [[4., 5., 6.]],

        [[7., 8., 9.]]])
torch.Size([3, 1, 3])


In [3]:
reshape = tensor_3d.reshape((1, 9))
print(reshape)
print(reshape.size())

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
torch.Size([1, 9])


In [4]:
view1 = tensor_3d.view((1, 9))
print(view1)
print(view1.size())

# the size -1 表示本维度从其他维度推断
view2 = tensor_3d.view((3, 3, -1))
print(view2)
print(view2.size())

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
torch.Size([1, 9])
tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]],

        [[7.],
         [8.],
         [9.]]])
torch.Size([3, 3, 1])


In [8]:
# transpose操作一般还是操作相邻的才对
print(tensor_3d)
print(tensor_3d.size())
transpose = torch.transpose(tensor_3d, 0, 1)
print(transpose)
print(transpose.size())
transpose2 = torch.transpose(tensor_3d, -2, -1)
print(transpose2)
print(transpose2.size())

tensor([[[1., 2., 3.]],

        [[4., 5., 6.]],

        [[7., 8., 9.]]])
torch.Size([3, 1, 3])
tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])
torch.Size([1, 3, 3])
tensor([[[1.],
         [2.],
         [3.]],

        [[4.],
         [5.],
         [6.]],

        [[7.],
         [8.],
         [9.]]])
torch.Size([3, 3, 1])


In [16]:
# squeeze1是无效的。
squeeze1 = torch.squeeze(tensor_3d, dim=0)
print(squeeze1)
print(squeeze1.size())

tensor([[[1., 2., 3.]],

        [[4., 5., 6.]],

        [[7., 8., 9.]]])
torch.Size([3, 1, 3])


In [17]:
squeeze2 = torch.squeeze(tensor_3d, dim=1)
print(squeeze2)
print(squeeze2.size())

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])
torch.Size([3, 3])


In [18]:
unsqueeze = torch.unsqueeze(squeeze2, dim=0)
print(unsqueeze)
print(unsqueeze.size())

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]])
torch.Size([1, 3, 3])


In [21]:
"""
怎么理解squeeze和unsqueeze:
If you look at the shape of the array before and after, 
you see that before it was (4,) and after it is (1, 4) (when second parameter is 0)
and (4, 1) (when second parameter is 1). So a 1 was inserted in the shape of the array at axis 0 or 1, 
depending on the value of the second parameter.
That is opposite of np.squeeze() which removes axes of size 1 (singletons).
为什么需要squeeze/unsqueeze?我觉得应该是为了满足某些layer的input的shape的要求，老是需要调整
shape。
"""
g = torch.zeros(4)
print(g)
# g shape is (4)
g_unsqueezz_dim0 = torch.unsqueeze(g, dim=0)
# 在(4)的0位置插入一个1，变成(1, 4)
g_unsqueezz_dim1 = torch.unsqueeze(g, dim=1)
# 在(4)的1位置插入1，变成(4,1)
print(g_unsqueezz_dim0)
print(g_unsqueezz_dim1)
g_squeeze_dim0 = torch.squeeze(g_unsqueezz_dim0, dim=0)
print(g_squeeze_dim0)
# (1, 4)的0位置移除1，变成(4)
g_squeeze_dim1 = torch.squeeze(g_unsqueezz_dim1, dim=1)
# (4, 1)位置移除1，变成(4)
print(g_squeeze_dim1)

h = torch.Tensor([[1, 2, 3], [4, 5, 6]])
print(h)
h_dim0 = torch.unsqueeze(h, dim=0)
print(h_dim0)
# (1, 2, 3)
h_dim1 = torch.unsqueeze(h, dim=1)
print(h_dim1)
# (2, 1, 3)

tensor([0., 0., 0., 0.])
tensor([[0., 0., 0., 0.]])
tensor([[0.],
        [0.],
        [0.],
        [0.]])
tensor([0., 0., 0., 0.])
tensor([0., 0., 0., 0.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[[1., 2., 3.],
         [4., 5., 6.]]])
tensor([[[1., 2., 3.]],

        [[4., 5., 6.]]])
